### ISSUE TITLE
Hytrix Steam not exposed as described

### ISSUE THREAD

**Issue by ewolff** [spring-cloud-samples/hystrix-dashboard#2]
https://github.com/spring-cloud-samples/tests/tree/master/hystrix is the sample Hystrix app and should expose a Hystrix Stream. However, http://localhost:8080/hystrix.stream returns a 500 and it is not possible to use the app with the Dashboard. Log message do not suggest that any bean is started to deal with this URL.

**Comment by ewolff** [comment]
The problem is: It only works if spring-boot-starter-actuator is among the dependencies. This appears to be undocumented.

**Comment by spencergibb** [comment]
fixed with https://github.com/spring-cloud-samples/tests/commit/3465dfc707ebe911442e2ff753b4a1303ba4c98b and https://github.com/spring-cloud/spring-cloud-netflix/commit/9623c838853253ccbfc53497d1c5c676909e3d9d

Thanks @ewolff!
