### ISSUE TITLE
problem about static files urls

### ISSUE THREAD

**Issue by shinigami1992** [spring-cloud-samples/hystrix-dashboard#4]
Hi guys

I can enable hystrix dashboard successfuly. 

But in production environment, my service is after zuul with this domain "http://sample_domain/service_name/..." which cause static files like jquery.js don't load successfully.
(It wants to download files for example from http://sample_domain/jquery.js instead of http://sample_domain/service_name/jquery.js)

Is there any way to fix this issue by for example overriding base urls of static files or ...?

Thanks.

**Comment by spencergibb** [comment]
unrelated to hystrix-dashboard
