### ISSUE TITLE
Monitor Stream button not working, Dashboard page forever loading

### ISSUE THREAD

**Issue by yangzii0920** [spring-cloud-samples/hystrix-dashboard#5]
Hi,

In my project, I have a **REST service A on port 8888**, consumed by a **Hystrix application B on port 8000**. They work functionally correct as I got the expected message. 

However, I have issue with Hystrix Dashboard. First I tried to make B as a Hystrix Dashboard application by adding the `@EnableHystrixDashboard` annotation. I could open the Hystrix Dashboard home page on http://B:8000/hystrix.stream but there were just text data.

I though an explicit Hystrix Dashboard application might be needed so I created Hystrix Dashboard application C on port 8081 by adding the `@EnableHystrixDashboard` annotation. Again, the http://C:8081/hystrix.stream worked, yet the Monitor Stream button not working. 

If I manually type http://hystrix-dashboard-app:port/hystrix/monitor?stream=http%3A%2FHystrixApp%3Aport/%2Fhystrix.stream it would take me to the statistic page but forever it shows 'Loading...'

Please give any thought you have. Thanks.

**Comment by spencergibb** [comment]
Are there any messages or errors in the javascript console?

**Comment by yangzii0920** [comment]
Got a 404 on loading http://localhost:8081/webjars/jquery/2.1.1/jquery.min.js. 

Tried using CDN https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js. Then when I click, it says $ is not defined regarding to the event.

I simply added a `@EnableHystrixDashboard` annotation in a SpringBoot application without anything else. Could it be the problem?

**Comment by spencergibb** [comment]
What version are you using?

**Comment by yangzii0920** [comment]
from what I can see it's Spring Boot 1.5.3.Release.

**Comment by spencergibb** [comment]
version of spring cloud?

**Comment by yangzii0920** [comment]
It's Dalston.release.

**Comment by yangzii0920** [comment]
Problem solved. The jar file in ~/.m2/repository/org/webjar/jquery/2.1.1/jquery-2.1.1.jar is broken.

**Comment by bsushant-athena** [comment]
hey  @yangzii0920 how did you solve the problem ? I'm also facing the same issue ? 
@spencergibb

**Comment by yangzii0920** [comment]
Simply delete the jar under maven repositories

**Comment by bsushant-athena** [comment]
I deleted the jar but still same issue, also apart from that jar there are these files
jquery-2.1.1.jar.sha1 ,jquery-2.1.1.pom ,jquery-2.1.1.pom.sha1

shall I delete them as well?
@yangzii0920

**Comment by bsushant-athena** [comment]
Even after deleting them , I still see this error in chrome console:
hystrix:14 Uncaught ReferenceError: $ is not defined
    at sendToMonitor (hystrix:14)
    at HTMLButtonElement.onclick (hystrix:50)

@spencergibb

**Comment by wwwlll2001** [comment]
Facing same issue, any updates?
@spencergibb

**Comment by MateuszRasinski** [comment]
You probably have no URLs mapped or map only "/". When you add any mapping the problem will be resolved.

**Comment by gauravsingh21** [comment]
There should be no mapping with default render("/")
example change @GetMapping to @GetMapping("/SomethingElse"). 
This will resolve your issue.

**Comment by gauravsingh21** [comment]
There should be no mapping with default render("/")
example:-  change @GetMapping to @GetMapping("/SomethingElse").
This will resolve your issue.

**Comment by vmisra2018** [comment]
@spencergibb  I am trying this sample  https://github.com/piomin/sample-spring-microservices/tree/hystrix .  I  updated this with Hoxton.RELEASE and springboot 2.2.4.RELEASE. (With only code change of removing Sleuth config AlwaysSampler (as could not find in deps with latest change).
When I go to hystrix dashboard http://localhost:2222/hystrix and then type in http://localhost:3333/actuator/hystrix.stream and hit on Monitor Stream and I see same issue as above mentioned.  I see Loading .... 

Looks like the above issue
Can you please help?

I see in logs of account service
2020-02-13 16:12:15.753 INFO [account-service,ff3f4d0dc9340df9,ff3f4d0dc9340df9,false] 9431 --- [nio-2222-exec-3] ashboardConfiguration$ProxyStreamServlet :

Proxy opening connection to: http://localhost:3333/actuator/hystrix.stream

Also, first I made hystrix.stream enabled on customer but not effect on dashboard UI .It kees saying Loading...
and then on account (I think it should be on account service side ) still no effect

application.yml
```
//omitting other entries
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
```
